[package]
name = "parse-ber-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptographic-message-syntax = "0.9"
x509-certificate = "0.8"
openssl = "0.10"
